name: CI

on:
  pull_request:
    branches: [main, next, beta, alpha]

env:
  FORCE_COLOR: 3
  VITE_PROXY_URL: https://photo-info-image-proxy.tyom.workers.dev

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Check code
        run: pnpm check

      - name: Test
        run: pnpm test
